/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRecruiterRouteImport } from './routes/_authenticated/recruiter'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedRecruiterReportsRouteImport } from './routes/_authenticated/recruiter.reports'
import { Route as AuthenticatedRecruiterRankingRouteImport } from './routes/_authenticated/recruiter.ranking'
import { Route as AuthenticatedRecruiterMessagesRouteImport } from './routes/_authenticated/recruiter.messages'
import { Route as AuthenticatedRecruiterCompareRouteImport } from './routes/_authenticated/recruiter.compare'
import { Route as AuthenticatedRecruiterCandidatesRouteImport } from './routes/_authenticated/recruiter.candidates'
import { Route as AuthenticatedRecruiterAnalyticsRouteImport } from './routes/_authenticated/recruiter.analytics'
import { Route as AuthenticatedDashboardSkillsRouteImport } from './routes/_authenticated/dashboard.skills'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardRoadmapRouteImport } from './routes/_authenticated/dashboard.roadmap'
import { Route as AuthenticatedDashboardResumeBuilderRouteImport } from './routes/_authenticated/dashboard.resume-builder'
import { Route as AuthenticatedDashboardResumeRouteImport } from './routes/_authenticated/dashboard.resume'
import { Route as AuthenticatedDashboardProjectsRouteImport } from './routes/_authenticated/dashboard.projects'
import { Route as AuthenticatedDashboardPlacementRouteImport } from './routes/_authenticated/dashboard.placement'
import { Route as AuthenticatedDashboardMockInterviewRouteImport } from './routes/_authenticated/dashboard.mock-interview'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard.messages'
import { Route as AuthenticatedDashboardJobsRouteImport } from './routes/_authenticated/dashboard.jobs'
import { Route as AuthenticatedDashboardInterviewsRouteImport } from './routes/_authenticated/dashboard.interviews'
import { Route as AuthenticatedDashboardInternshipsRouteImport } from './routes/_authenticated/dashboard.internships'
import { Route as AuthenticatedDashboardGithubRouteImport } from './routes/_authenticated/dashboard.github'
import { Route as AuthenticatedDashboardAssistantRouteImport } from './routes/_authenticated/dashboard.assistant'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecruiterRoute = AuthenticatedRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRecruiterReportsRoute =
  AuthenticatedRecruiterReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterRankingRoute =
  AuthenticatedRecruiterRankingRouteImport.update({
    id: '/ranking',
    path: '/ranking',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterMessagesRoute =
  AuthenticatedRecruiterMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterCompareRoute =
  AuthenticatedRecruiterCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterCandidatesRoute =
  AuthenticatedRecruiterCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterAnalyticsRoute =
  AuthenticatedRecruiterAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedDashboardSkillsRoute =
  AuthenticatedDashboardSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRoadmapRoute =
  AuthenticatedDashboardRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardResumeBuilderRoute =
  AuthenticatedDashboardResumeBuilderRouteImport.update({
    id: '/resume-builder',
    path: '/resume-builder',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardResumeRoute =
  AuthenticatedDashboardResumeRouteImport.update({
    id: '/resume',
    path: '/resume',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProjectsRoute =
  AuthenticatedDashboardProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPlacementRoute =
  AuthenticatedDashboardPlacementRouteImport.update({
    id: '/placement',
    path: '/placement',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMockInterviewRoute =
  AuthenticatedDashboardMockInterviewRouteImport.update({
    id: '/mock-interview',
    path: '/mock-interview',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardJobsRoute =
  AuthenticatedDashboardJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInterviewsRoute =
  AuthenticatedDashboardInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInternshipsRoute =
  AuthenticatedDashboardInternshipsRouteImport.update({
    id: '/internships',
    path: '/internships',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGithubRoute =
  AuthenticatedDashboardGithubRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAssistantRoute =
  AuthenticatedDashboardAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/recruiter': typeof AuthenticatedRecruiterRouteWithChildren
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/assistant': typeof AuthenticatedDashboardAssistantRoute
  '/dashboard/github': typeof AuthenticatedDashboardGithubRoute
  '/dashboard/internships': typeof AuthenticatedDashboardInternshipsRoute
  '/dashboard/interviews': typeof AuthenticatedDashboardInterviewsRoute
  '/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/mock-interview': typeof AuthenticatedDashboardMockInterviewRoute
  '/dashboard/placement': typeof AuthenticatedDashboardPlacementRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/dashboard/resume': typeof AuthenticatedDashboardResumeRoute
  '/dashboard/resume-builder': typeof AuthenticatedDashboardResumeBuilderRoute
  '/dashboard/roadmap': typeof AuthenticatedDashboardRoadmapRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/skills': typeof AuthenticatedDashboardSkillsRoute
  '/recruiter/analytics': typeof AuthenticatedRecruiterAnalyticsRoute
  '/recruiter/candidates': typeof AuthenticatedRecruiterCandidatesRoute
  '/recruiter/compare': typeof AuthenticatedRecruiterCompareRoute
  '/recruiter/messages': typeof AuthenticatedRecruiterMessagesRoute
  '/recruiter/ranking': typeof AuthenticatedRecruiterRankingRoute
  '/recruiter/reports': typeof AuthenticatedRecruiterReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/recruiter': typeof AuthenticatedRecruiterRouteWithChildren
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/assistant': typeof AuthenticatedDashboardAssistantRoute
  '/dashboard/github': typeof AuthenticatedDashboardGithubRoute
  '/dashboard/internships': typeof AuthenticatedDashboardInternshipsRoute
  '/dashboard/interviews': typeof AuthenticatedDashboardInterviewsRoute
  '/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/mock-interview': typeof AuthenticatedDashboardMockInterviewRoute
  '/dashboard/placement': typeof AuthenticatedDashboardPlacementRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/dashboard/resume': typeof AuthenticatedDashboardResumeRoute
  '/dashboard/resume-builder': typeof AuthenticatedDashboardResumeBuilderRoute
  '/dashboard/roadmap': typeof AuthenticatedDashboardRoadmapRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/skills': typeof AuthenticatedDashboardSkillsRoute
  '/recruiter/analytics': typeof AuthenticatedRecruiterAnalyticsRoute
  '/recruiter/candidates': typeof AuthenticatedRecruiterCandidatesRoute
  '/recruiter/compare': typeof AuthenticatedRecruiterCompareRoute
  '/recruiter/messages': typeof AuthenticatedRecruiterMessagesRoute
  '/recruiter/ranking': typeof AuthenticatedRecruiterRankingRoute
  '/recruiter/reports': typeof AuthenticatedRecruiterReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/recruiter': typeof AuthenticatedRecruiterRouteWithChildren
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/dashboard/assistant': typeof AuthenticatedDashboardAssistantRoute
  '/_authenticated/dashboard/github': typeof AuthenticatedDashboardGithubRoute
  '/_authenticated/dashboard/internships': typeof AuthenticatedDashboardInternshipsRoute
  '/_authenticated/dashboard/interviews': typeof AuthenticatedDashboardInterviewsRoute
  '/_authenticated/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/_authenticated/dashboard/mock-interview': typeof AuthenticatedDashboardMockInterviewRoute
  '/_authenticated/dashboard/placement': typeof AuthenticatedDashboardPlacementRoute
  '/_authenticated/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/_authenticated/dashboard/resume': typeof AuthenticatedDashboardResumeRoute
  '/_authenticated/dashboard/resume-builder': typeof AuthenticatedDashboardResumeBuilderRoute
  '/_authenticated/dashboard/roadmap': typeof AuthenticatedDashboardRoadmapRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/skills': typeof AuthenticatedDashboardSkillsRoute
  '/_authenticated/recruiter/analytics': typeof AuthenticatedRecruiterAnalyticsRoute
  '/_authenticated/recruiter/candidates': typeof AuthenticatedRecruiterCandidatesRoute
  '/_authenticated/recruiter/compare': typeof AuthenticatedRecruiterCompareRoute
  '/_authenticated/recruiter/messages': typeof AuthenticatedRecruiterMessagesRoute
  '/_authenticated/recruiter/ranking': typeof AuthenticatedRecruiterRankingRoute
  '/_authenticated/recruiter/reports': typeof AuthenticatedRecruiterReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/login'
    | '/mcp'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/solutions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/recruiter'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/assistant'
    | '/dashboard/github'
    | '/dashboard/internships'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/messages'
    | '/dashboard/mock-interview'
    | '/dashboard/placement'
    | '/dashboard/projects'
    | '/dashboard/resume'
    | '/dashboard/resume-builder'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard/skills'
    | '/recruiter/analytics'
    | '/recruiter/candidates'
    | '/recruiter/compare'
    | '/recruiter/messages'
    | '/recruiter/ranking'
    | '/recruiter/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/login'
    | '/mcp'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/solutions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/recruiter'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/assistant'
    | '/dashboard/github'
    | '/dashboard/internships'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/messages'
    | '/dashboard/mock-interview'
    | '/dashboard/placement'
    | '/dashboard/projects'
    | '/dashboard/resume'
    | '/dashboard/resume-builder'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard/skills'
    | '/recruiter/analytics'
    | '/recruiter/candidates'
    | '/recruiter/compare'
    | '/recruiter/messages'
    | '/recruiter/ranking'
    | '/recruiter/reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/login'
    | '/mcp'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/solutions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/_authenticated/recruiter'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/dashboard/assistant'
    | '/_authenticated/dashboard/github'
    | '/_authenticated/dashboard/internships'
    | '/_authenticated/dashboard/interviews'
    | '/_authenticated/dashboard/jobs'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/mock-interview'
    | '/_authenticated/dashboard/placement'
    | '/_authenticated/dashboard/projects'
    | '/_authenticated/dashboard/resume'
    | '/_authenticated/dashboard/resume-builder'
    | '/_authenticated/dashboard/roadmap'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/skills'
    | '/_authenticated/recruiter/analytics'
    | '/_authenticated/recruiter/candidates'
    | '/_authenticated/recruiter/compare'
    | '/_authenticated/recruiter/messages'
    | '/_authenticated/recruiter/ranking'
    | '/_authenticated/recruiter/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recruiter': {
      id: '/_authenticated/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof AuthenticatedRecruiterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recruiter/reports': {
      id: '/_authenticated/recruiter/reports'
      path: '/reports'
      fullPath: '/recruiter/reports'
      preLoaderRoute: typeof AuthenticatedRecruiterReportsRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/ranking': {
      id: '/_authenticated/recruiter/ranking'
      path: '/ranking'
      fullPath: '/recruiter/ranking'
      preLoaderRoute: typeof AuthenticatedRecruiterRankingRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/messages': {
      id: '/_authenticated/recruiter/messages'
      path: '/messages'
      fullPath: '/recruiter/messages'
      preLoaderRoute: typeof AuthenticatedRecruiterMessagesRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/compare': {
      id: '/_authenticated/recruiter/compare'
      path: '/compare'
      fullPath: '/recruiter/compare'
      preLoaderRoute: typeof AuthenticatedRecruiterCompareRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/candidates': {
      id: '/_authenticated/recruiter/candidates'
      path: '/candidates'
      fullPath: '/recruiter/candidates'
      preLoaderRoute: typeof AuthenticatedRecruiterCandidatesRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/analytics': {
      id: '/_authenticated/recruiter/analytics'
      path: '/analytics'
      fullPath: '/recruiter/analytics'
      preLoaderRoute: typeof AuthenticatedRecruiterAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/dashboard/skills': {
      id: '/_authenticated/dashboard/skills'
      path: '/skills'
      fullPath: '/dashboard/skills'
      preLoaderRoute: typeof AuthenticatedDashboardSkillsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/roadmap': {
      id: '/_authenticated/dashboard/roadmap'
      path: '/roadmap'
      fullPath: '/dashboard/roadmap'
      preLoaderRoute: typeof AuthenticatedDashboardRoadmapRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/resume-builder': {
      id: '/_authenticated/dashboard/resume-builder'
      path: '/resume-builder'
      fullPath: '/dashboard/resume-builder'
      preLoaderRoute: typeof AuthenticatedDashboardResumeBuilderRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/resume': {
      id: '/_authenticated/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof AuthenticatedDashboardResumeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/projects': {
      id: '/_authenticated/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/placement': {
      id: '/_authenticated/dashboard/placement'
      path: '/placement'
      fullPath: '/dashboard/placement'
      preLoaderRoute: typeof AuthenticatedDashboardPlacementRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/mock-interview': {
      id: '/_authenticated/dashboard/mock-interview'
      path: '/mock-interview'
      fullPath: '/dashboard/mock-interview'
      preLoaderRoute: typeof AuthenticatedDashboardMockInterviewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/jobs': {
      id: '/_authenticated/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof AuthenticatedDashboardJobsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/interviews': {
      id: '/_authenticated/dashboard/interviews'
      path: '/interviews'
      fullPath: '/dashboard/interviews'
      preLoaderRoute: typeof AuthenticatedDashboardInterviewsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/internships': {
      id: '/_authenticated/dashboard/internships'
      path: '/internships'
      fullPath: '/dashboard/internships'
      preLoaderRoute: typeof AuthenticatedDashboardInternshipsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/github': {
      id: '/_authenticated/dashboard/github'
      path: '/github'
      fullPath: '/dashboard/github'
      preLoaderRoute: typeof AuthenticatedDashboardGithubRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/assistant': {
      id: '/_authenticated/dashboard/assistant'
      path: '/assistant'
      fullPath: '/dashboard/assistant'
      preLoaderRoute: typeof AuthenticatedDashboardAssistantRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAssistantRoute: typeof AuthenticatedDashboardAssistantRoute
  AuthenticatedDashboardGithubRoute: typeof AuthenticatedDashboardGithubRoute
  AuthenticatedDashboardInternshipsRoute: typeof AuthenticatedDashboardInternshipsRoute
  AuthenticatedDashboardInterviewsRoute: typeof AuthenticatedDashboardInterviewsRoute
  AuthenticatedDashboardJobsRoute: typeof AuthenticatedDashboardJobsRoute
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRoute
  AuthenticatedDashboardMockInterviewRoute: typeof AuthenticatedDashboardMockInterviewRoute
  AuthenticatedDashboardPlacementRoute: typeof AuthenticatedDashboardPlacementRoute
  AuthenticatedDashboardProjectsRoute: typeof AuthenticatedDashboardProjectsRoute
  AuthenticatedDashboardResumeRoute: typeof AuthenticatedDashboardResumeRoute
  AuthenticatedDashboardResumeBuilderRoute: typeof AuthenticatedDashboardResumeBuilderRoute
  AuthenticatedDashboardRoadmapRoute: typeof AuthenticatedDashboardRoadmapRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSkillsRoute: typeof AuthenticatedDashboardSkillsRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAssistantRoute: AuthenticatedDashboardAssistantRoute,
    AuthenticatedDashboardGithubRoute: AuthenticatedDashboardGithubRoute,
    AuthenticatedDashboardInternshipsRoute:
      AuthenticatedDashboardInternshipsRoute,
    AuthenticatedDashboardInterviewsRoute:
      AuthenticatedDashboardInterviewsRoute,
    AuthenticatedDashboardJobsRoute: AuthenticatedDashboardJobsRoute,
    AuthenticatedDashboardMessagesRoute: AuthenticatedDashboardMessagesRoute,
    AuthenticatedDashboardMockInterviewRoute:
      AuthenticatedDashboardMockInterviewRoute,
    AuthenticatedDashboardPlacementRoute: AuthenticatedDashboardPlacementRoute,
    AuthenticatedDashboardProjectsRoute: AuthenticatedDashboardProjectsRoute,
    AuthenticatedDashboardResumeRoute: AuthenticatedDashboardResumeRoute,
    AuthenticatedDashboardResumeBuilderRoute:
      AuthenticatedDashboardResumeBuilderRoute,
    AuthenticatedDashboardRoadmapRoute: AuthenticatedDashboardRoadmapRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardSkillsRoute: AuthenticatedDashboardSkillsRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRecruiterRouteChildren {
  AuthenticatedRecruiterAnalyticsRoute: typeof AuthenticatedRecruiterAnalyticsRoute
  AuthenticatedRecruiterCandidatesRoute: typeof AuthenticatedRecruiterCandidatesRoute
  AuthenticatedRecruiterCompareRoute: typeof AuthenticatedRecruiterCompareRoute
  AuthenticatedRecruiterMessagesRoute: typeof AuthenticatedRecruiterMessagesRoute
  AuthenticatedRecruiterRankingRoute: typeof AuthenticatedRecruiterRankingRoute
  AuthenticatedRecruiterReportsRoute: typeof AuthenticatedRecruiterReportsRoute
}

const AuthenticatedRecruiterRouteChildren: AuthenticatedRecruiterRouteChildren =
  {
    AuthenticatedRecruiterAnalyticsRoute: AuthenticatedRecruiterAnalyticsRoute,
    AuthenticatedRecruiterCandidatesRoute:
      AuthenticatedRecruiterCandidatesRoute,
    AuthenticatedRecruiterCompareRoute: AuthenticatedRecruiterCompareRoute,
    AuthenticatedRecruiterMessagesRoute: AuthenticatedRecruiterMessagesRoute,
    AuthenticatedRecruiterRankingRoute: AuthenticatedRecruiterRankingRoute,
    AuthenticatedRecruiterReportsRoute: AuthenticatedRecruiterReportsRoute,
  }

const AuthenticatedRecruiterRouteWithChildren =
  AuthenticatedRecruiterRoute._addFileChildren(
    AuthenticatedRecruiterRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedRecruiterRoute: typeof AuthenticatedRecruiterRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedRecruiterRoute: AuthenticatedRecruiterRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
