/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterReportsRouteImport } from './routes/recruiter.reports'
import { Route as RecruiterRankingRouteImport } from './routes/recruiter.ranking'
import { Route as RecruiterMessagesRouteImport } from './routes/recruiter.messages'
import { Route as RecruiterCompareRouteImport } from './routes/recruiter.compare'
import { Route as RecruiterCandidatesRouteImport } from './routes/recruiter.candidates'
import { Route as RecruiterAnalyticsRouteImport } from './routes/recruiter.analytics'
import { Route as DashboardSkillsRouteImport } from './routes/dashboard.skills'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRoadmapRouteImport } from './routes/dashboard.roadmap'
import { Route as DashboardResumeBuilderRouteImport } from './routes/dashboard.resume-builder'
import { Route as DashboardResumeRouteImport } from './routes/dashboard.resume'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardPlacementRouteImport } from './routes/dashboard.placement'
import { Route as DashboardMockInterviewRouteImport } from './routes/dashboard.mock-interview'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardInterviewsRouteImport } from './routes/dashboard.interviews'
import { Route as DashboardInternshipsRouteImport } from './routes/dashboard.internships'
import { Route as DashboardGithubRouteImport } from './routes/dashboard.github'
import { Route as DashboardAssistantRouteImport } from './routes/dashboard.assistant'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterReportsRoute = RecruiterReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterRankingRoute = RecruiterRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterMessagesRoute = RecruiterMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterCompareRoute = RecruiterCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterCandidatesRoute = RecruiterCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterAnalyticsRoute = RecruiterAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => RecruiterRoute,
} as any)
const DashboardSkillsRoute = DashboardSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoadmapRoute = DashboardRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeBuilderRoute = DashboardResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlacementRoute = DashboardPlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMockInterviewRoute = DashboardMockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInterviewsRoute = DashboardInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInternshipsRoute = DashboardInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGithubRoute = DashboardGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssistantRoute = DashboardAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => DashboardRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/github': typeof DashboardGithubRoute
  '/dashboard/internships': typeof DashboardInternshipsRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/mock-interview': typeof DashboardMockInterviewRoute
  '/dashboard/placement': typeof DashboardPlacementRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/resume-builder': typeof DashboardResumeBuilderRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/compare': typeof RecruiterCompareRoute
  '/recruiter/messages': typeof RecruiterMessagesRoute
  '/recruiter/ranking': typeof RecruiterRankingRoute
  '/recruiter/reports': typeof RecruiterReportsRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/github': typeof DashboardGithubRoute
  '/dashboard/internships': typeof DashboardInternshipsRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/mock-interview': typeof DashboardMockInterviewRoute
  '/dashboard/placement': typeof DashboardPlacementRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/resume-builder': typeof DashboardResumeBuilderRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/compare': typeof RecruiterCompareRoute
  '/recruiter/messages': typeof RecruiterMessagesRoute
  '/recruiter/ranking': typeof RecruiterRankingRoute
  '/recruiter/reports': typeof RecruiterReportsRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/github': typeof DashboardGithubRoute
  '/dashboard/internships': typeof DashboardInternshipsRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/mock-interview': typeof DashboardMockInterviewRoute
  '/dashboard/placement': typeof DashboardPlacementRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/resume-builder': typeof DashboardResumeBuilderRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/compare': typeof RecruiterCompareRoute
  '/recruiter/messages': typeof RecruiterMessagesRoute
  '/recruiter/ranking': typeof RecruiterRankingRoute
  '/recruiter/reports': typeof RecruiterReportsRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/mcp'
    | '/pricing'
    | '/recruiter'
    | '/signup'
    | '/solutions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/assistant'
    | '/dashboard/github'
    | '/dashboard/internships'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/messages'
    | '/dashboard/mock-interview'
    | '/dashboard/placement'
    | '/dashboard/projects'
    | '/dashboard/resume'
    | '/dashboard/resume-builder'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard/skills'
    | '/recruiter/analytics'
    | '/recruiter/candidates'
    | '/recruiter/compare'
    | '/recruiter/messages'
    | '/recruiter/ranking'
    | '/recruiter/reports'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/mcp'
    | '/pricing'
    | '/recruiter'
    | '/signup'
    | '/solutions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/assistant'
    | '/dashboard/github'
    | '/dashboard/internships'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/messages'
    | '/dashboard/mock-interview'
    | '/dashboard/placement'
    | '/dashboard/projects'
    | '/dashboard/resume'
    | '/dashboard/resume-builder'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard/skills'
    | '/recruiter/analytics'
    | '/recruiter/candidates'
    | '/recruiter/compare'
    | '/recruiter/messages'
    | '/recruiter/ranking'
    | '/recruiter/reports'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/mcp'
    | '/pricing'
    | '/recruiter'
    | '/signup'
    | '/solutions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/assistant'
    | '/dashboard/github'
    | '/dashboard/internships'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/messages'
    | '/dashboard/mock-interview'
    | '/dashboard/placement'
    | '/dashboard/projects'
    | '/dashboard/resume'
    | '/dashboard/resume-builder'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard/skills'
    | '/recruiter/analytics'
    | '/recruiter/candidates'
    | '/recruiter/compare'
    | '/recruiter/messages'
    | '/recruiter/ranking'
    | '/recruiter/reports'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  RecruiterRoute: typeof RecruiterRouteWithChildren
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/reports': {
      id: '/recruiter/reports'
      path: '/reports'
      fullPath: '/recruiter/reports'
      preLoaderRoute: typeof RecruiterReportsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/ranking': {
      id: '/recruiter/ranking'
      path: '/ranking'
      fullPath: '/recruiter/ranking'
      preLoaderRoute: typeof RecruiterRankingRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/messages': {
      id: '/recruiter/messages'
      path: '/messages'
      fullPath: '/recruiter/messages'
      preLoaderRoute: typeof RecruiterMessagesRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/compare': {
      id: '/recruiter/compare'
      path: '/compare'
      fullPath: '/recruiter/compare'
      preLoaderRoute: typeof RecruiterCompareRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/candidates': {
      id: '/recruiter/candidates'
      path: '/candidates'
      fullPath: '/recruiter/candidates'
      preLoaderRoute: typeof RecruiterCandidatesRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/analytics': {
      id: '/recruiter/analytics'
      path: '/analytics'
      fullPath: '/recruiter/analytics'
      preLoaderRoute: typeof RecruiterAnalyticsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/dashboard/skills': {
      id: '/dashboard/skills'
      path: '/skills'
      fullPath: '/dashboard/skills'
      preLoaderRoute: typeof DashboardSkillsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roadmap': {
      id: '/dashboard/roadmap'
      path: '/roadmap'
      fullPath: '/dashboard/roadmap'
      preLoaderRoute: typeof DashboardRoadmapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume-builder': {
      id: '/dashboard/resume-builder'
      path: '/resume-builder'
      fullPath: '/dashboard/resume-builder'
      preLoaderRoute: typeof DashboardResumeBuilderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume': {
      id: '/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/placement': {
      id: '/dashboard/placement'
      path: '/placement'
      fullPath: '/dashboard/placement'
      preLoaderRoute: typeof DashboardPlacementRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mock-interview': {
      id: '/dashboard/mock-interview'
      path: '/mock-interview'
      fullPath: '/dashboard/mock-interview'
      preLoaderRoute: typeof DashboardMockInterviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/interviews': {
      id: '/dashboard/interviews'
      path: '/interviews'
      fullPath: '/dashboard/interviews'
      preLoaderRoute: typeof DashboardInterviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/internships': {
      id: '/dashboard/internships'
      path: '/internships'
      fullPath: '/dashboard/internships'
      preLoaderRoute: typeof DashboardInternshipsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/github': {
      id: '/dashboard/github'
      path: '/github'
      fullPath: '/dashboard/github'
      preLoaderRoute: typeof DashboardGithubRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assistant': {
      id: '/dashboard/assistant'
      path: '/assistant'
      fullPath: '/dashboard/assistant'
      preLoaderRoute: typeof DashboardAssistantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAssistantRoute: typeof DashboardAssistantRoute
  DashboardGithubRoute: typeof DashboardGithubRoute
  DashboardInternshipsRoute: typeof DashboardInternshipsRoute
  DashboardInterviewsRoute: typeof DashboardInterviewsRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMockInterviewRoute: typeof DashboardMockInterviewRoute
  DashboardPlacementRoute: typeof DashboardPlacementRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardResumeBuilderRoute: typeof DashboardResumeBuilderRoute
  DashboardRoadmapRoute: typeof DashboardRoadmapRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSkillsRoute: typeof DashboardSkillsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssistantRoute: DashboardAssistantRoute,
  DashboardGithubRoute: DashboardGithubRoute,
  DashboardInternshipsRoute: DashboardInternshipsRoute,
  DashboardInterviewsRoute: DashboardInterviewsRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMockInterviewRoute: DashboardMockInterviewRoute,
  DashboardPlacementRoute: DashboardPlacementRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardResumeBuilderRoute: DashboardResumeBuilderRoute,
  DashboardRoadmapRoute: DashboardRoadmapRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSkillsRoute: DashboardSkillsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface RecruiterRouteChildren {
  RecruiterAnalyticsRoute: typeof RecruiterAnalyticsRoute
  RecruiterCandidatesRoute: typeof RecruiterCandidatesRoute
  RecruiterCompareRoute: typeof RecruiterCompareRoute
  RecruiterMessagesRoute: typeof RecruiterMessagesRoute
  RecruiterRankingRoute: typeof RecruiterRankingRoute
  RecruiterReportsRoute: typeof RecruiterReportsRoute
}

const RecruiterRouteChildren: RecruiterRouteChildren = {
  RecruiterAnalyticsRoute: RecruiterAnalyticsRoute,
  RecruiterCandidatesRoute: RecruiterCandidatesRoute,
  RecruiterCompareRoute: RecruiterCompareRoute,
  RecruiterMessagesRoute: RecruiterMessagesRoute,
  RecruiterRankingRoute: RecruiterRankingRoute,
  RecruiterReportsRoute: RecruiterReportsRoute,
}

const RecruiterRouteWithChildren = RecruiterRoute._addFileChildren(
  RecruiterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  RecruiterRoute: RecruiterRouteWithChildren,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
